# Generated by Django 5.1 on 2024-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=50)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
