# Generated by Django 5.1 on 2024-08-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=50)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Adventure Photography', 'Adventure Photography'), ('Aerial Photography', 'Aerial Photography'), ('Astro Photography', 'Astro Photography'), ('Automotive Photography', 'Automotive Photography'), ('Commercial Photography', 'Commercial Photography'), ('Documentary Photography', 'Documentary Photography'), ('Event Photography', 'Event Photography'), ('Fashion Photography', 'Fashion Photography'), ('Fine Art Photography', 'Fine Art Photography'), ('Food Photography', 'Food Photography'), ('Industrial Photography', 'Industrial Photography'), ('Landscape Photography', 'Landscape Photography'), ('Medical Photography', 'Medical Photography'), ('Pet Photography', 'Pet Photography'), ('Photojournalist', 'Photojournalist'), ('Portrait Photography', 'Portrait Photography'), ('Product Photography', 'Product Photography'), ('Real Estate Photography', 'Real Estate Photography'), ('Scientific Photography', 'Scientific Photography'), ('Sports Photography', 'Sports Photography'), ('Stock Photography', 'Stock Photography'), ('Street Photography', 'Street Photography'), ('Travel Photography', 'Travel Photography'), ('War Photography', 'War Photography'), ('Wedding Photography', 'Wedding Photography'), ('Wildlife Photography', 'Wildlife Photography')], max_length=1000, null=True)),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photographer.portfolio')),
            ],
        ),
    ]
