# Generated by Django 5.1 on 2024-09-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('photographer', '0003_ratings_photographer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fees'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=1000, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('photographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photographer.photographer')),
            ],
        ),
    ]
