# Generated by Django 5.1 on 2024-11-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0005_rename_ratings_rating_photographer_is_deleted_and_more'),
    ]

    # operations = [
    #     migrations.RenameModel(
    #         old_name='Rating',
    #         new_name='Ratings',
    #     ),
    # ]
