# Generated by Django 5.1 on 2024-11-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0006_rename_rating_ratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
