# Generated by Django 5.1 on 2024-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0007_rename_ratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
