# Generated by Django 5.1 on 2024-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0008_photographer_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='rating',
            field=models.ManyToManyField(to='photographer.rating'),
        ),
    ]
