# Generated by Django 5.1 on 2024-11-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0009_alter_photographer_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-rating']},
        ),
    ]
