# Generated by Django 5.1 on 2024-11-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0010_alter_rating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['rating']},
        ),
    ]
