# Generated by Django 5.1 on 2024-11-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0011_alter_rating_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='rating',
        ),
        migrations.AddField(
            model_name='photographer',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photographer.rating'),
        ),
    ]
