# Generated by Django 5.1 on 2024-12-03 18:57

import django.db.models.deletion
import photographer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0013_photographer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=photographer.models.upload_to_directory),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photographer.photographer'),
        ),
    ]
